MKSHELL=/bin/bash

(.*)\\.subsampled_(.*)\\.vcf:RQ: \\1\\.subsampled_\\2\\.vcf\\.tmp \\1\\.vcf\\.gz
	echo "[DEBUG] extracting sample $stem2 from $stem1.vcf.gz"
	bcftools view \
		--samples $stem2 \
		--exclude-uncalled \
		$stem1.vcf.gz \
		--min-ac 1 \
	| bcftools annotate \
		 --remove ID,QUAL,FILTER,INFO,FORMAT/GT \
	> $target.build \
	&& mv $target.build $target
